Clean up output of quickchick-expectfailure

diff --git a/scripts/quickchick-expectfailure b/scripts/quickchick-expectfailure
--- a/scripts/quickchick-expectfailure
+++ b/scripts/quickchick-expectfailure
@@ -10,8 +10,8 @@ mkdir -p $QC_OUT_DIR/
 
 LOG_FILE=$QC_OUT_DIR/testlog-${1##*/}-${2##*/}
 
-echo "Mutant $2: testing..."
+echo "Mutant $2: Testing..."
 QC_MUTANT=$2 $1 > $LOG_FILE
 grep -q '^*** Failed' $LOG_FILE \
-  || (echo "Mutant $2: Tests passed, but failure was expected"; exit 1)
-echo "Mutant $2: killed!"
+  || (echo "Mutant $2: Tests passed, but failure was expected."; exit 1)
+echo "Mutant $2: Killed!"
